version: "3.3"

services:
  nginx-custom-path:
    build:
      context: .
    container_name: nginx-custom-path
    healthcheck:
      test: curl http://localhost:80
      interval: 1s
    restart: unless-stopped
    networks:
      - ocelot-net

networks:
  ocelot-net:
    external: true