# Tasks:
# Connect with KeyCloak via OIDC -> do all low level preparations beforehand, the git pull of the plugin etc
# Discourse GUI > Admin > Settings > Search for "login" > Select "Login" > uncheck "allow new registrations" -> to the docs
# Problem is, that this did not work as I expected. Maybe try later. again.

# This file has been modified by ChristophBaier.
# The original file was obtained from https://github.com/bitnami/containers/tree/main/bitnami/discourse and is licensed under the Apache License 2.0.
# You may obtain a copy of the License at http://www.apache.org/licenses/LICENSE-2.0

version: '3'

services:
  postgresql:
    image: docker.io/bitnami/postgresql:16.1.0
    restart: unless-stopped
    container_name: discourse-postgresql
    volumes:
      - 'postgresql_data:/bitnami/postgresql'
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - POSTGRESQL_USERNAME=bn_discourse
      - POSTGRESQL_DATABASE=bitnami_discourse
    networks:
      - discourse-net

  redis:
    image: docker.io/bitnami/redis:7.0.15
    restart: unless-stopped
    container_name: discourse-redis
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - 'redis_data:/bitnami/redis'
    networks:
      - discourse-net

  discourse:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    container_name: discourse
    volumes:
      - 'discourse_data:/bitnami/discourse'
    depends_on:
      - postgresql
      - redis
    healthcheck:
      test: curl http://localhost:3000
      interval: 1s
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - DISCOURSE_HOST=discourse.localhost
      - DISCOURSE_DATABASE_HOST=discourse-postgresql
      - DISCOURSE_DATABASE_PORT_NUMBER=5432
      - DISCOURSE_DATABASE_USER=bn_discourse
      - DISCOURSE_DATABASE_NAME=bitnami_discourse
      - DISCOURSE_REDIS_HOST=discourse-redis
      - DISCOURSE_REDIS_PORT_NUMBER=6379
      - POSTGRESQL_CLIENT_POSTGRES_USER=postgres
      - POSTGRESQL_CLIENT_CREATE_DATABASE_NAME=bitnami_discourse
      - POSTGRESQL_CLIENT_CREATE_DATABASE_EXTENSIONS=hstore,pg_trgm
      - DISCOURSE_USERNAME=admin
      - DISCOURSE_PASSWORD=password12345
      - DISCOURSE_EMAIL=admin@example.com
    networks:
      - ocelot-net
      - discourse-net

  sidekiq:
    image: docker.io/bitnami/discourse:3.1.3
    restart: unless-stopped
    container_name: discourse-sidekiq
    depends_on:
      - discourse
    volumes:
      - 'sidekiq_data:/bitnami/discourse'
    command: /opt/bitnami/scripts/discourse-sidekiq/run.sh
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - DISCOURSE_HOST=discourse
      - DISCOURSE_DATABASE_HOST=discourse-postgresql
      - DISCOURSE_DATABASE_PORT_NUMBER=5432
      - DISCOURSE_DATABASE_USER=bn_discourse
      - DISCOURSE_DATABASE_NAME=bitnami_discourse
      - DISCOURSE_REDIS_HOST=discourse-redis
      - DISCOURSE_REDIS_PORT_NUMBER=6379
    networks:
      - discourse-net

volumes:
  postgresql_data:
  redis_data:
  discourse_data:
  sidekiq_data:

networks:
  discourse-net:
  ocelot-net:
    external: true