name: CI

on:
  push:
    branches:
      - '**'
  schedule:
    - cron: '0 0 * * 3'

jobs:
  ci-tests:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/setup
      - name: Run CI Tests
        run: |
          cd src/ci-runner
          go build
          ./ci-runner test ci
